// Generated by ts-to-zod
import { z } from "zod";

export const committeeSchema = z.object({
  id: z.string(),
  name: z.string(),
  code: z.string(),
  passphrase: z.string(),
  chairId: z.string(),
  description: z.string().optional(),
  countries: z.array(z.string()),
  customCountries: z
    .record(
      z.object({
        name: z.string(),
        imageUrl: z.string(),
        emoji: z.string().optional(),
      })
    )
    .optional(),
});

export const votingSessionSchema = z.object({
  id: z.string(),
  committeeId: committeeSchema.shape.id,
  name: z.string(),
  description: z.string().optional(),
  isOpen: z.boolean(),
  startTime: z.date().optional(),
  endTime: z.date().optional(),
});

export const votingRecordSchema = z.object({
  countryCode: z.string(),
  sessionId: votingSessionSchema.shape.id,
  choice: z.union([z.literal("YAY"), z.literal("NAY"), z.literal("ABSTAIN")]),
});

export const votingSessionWithRecordsSchema = votingSessionSchema.and(
  z.object({
    records: z.array(votingRecordSchema),
  })
);
