// Generated by ts-to-zod
import { z } from "zod";

export const committeeSchema = z.object({
  id: z.string(),
  name: z.string(),
  topics: z.array(z.string()),
  passphrase: z.string(),
});

export const participantSchema = z.object({
  committeeId: committeeSchema.shape.id,
  countryCode: z.string(),
});

export const votingSessionSchema = z.object({
  id: z.string(),
  committeeId: committeeSchema.shape.id,
  topic: z.string(),
  startTime: z.date(),
  endTime: z.date(),
});

export const votingRecordSchema = z.object({
  id: z.string(),
  sessionId: votingSessionSchema.shape.id,
  countryCode: participantSchema.shape.countryCode,
  choice: z.union([z.literal("YAY"), z.literal("NAY"), z.literal("ABSTAIN")]),
});
